id: P8DAB2BAF
initial_creation_type: ocr
source_metadata:
  volumes:
    0709cf626b084bc789c0b0b42ba97e31:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: ཆོམ་རྐུན་བཅིང་བ།
      total_pages: 1648
      volume_number: 40
